# Use the recommended Flutter lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce good code style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    avoid_print: true
    always_specify_types: true
    unnecessary_null_checks: true
    prefer_typing_uninitialized_variables: true
    avoid_unused_constructor_parameters: true
    sort_constructors_first: true

    # Flutter-specific rules
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    avoid_redundant_argument_values: true

    # Optional: disable rules if needed
    # avoid_print: false
    # prefer_single_quotes: true