
name: expense_tracker_plus
description: A full-featured expense tracker with Firebase sync, charts, animations, ads and premium unlock.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.8.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.4.0
  shared_preferences: ^2.1.1
  fl_chart: ^0.55.0
  google_mobile_ads: ^2.3.0
  intl: ^0.18.0
  uuid: ^3.0.7
  in_app_purchase: ^3.2.3
  animated_list_plus: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
