name: expense_tracker
description: A Flutter expense tracker app.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  # Firebase (latest major versions)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # Ads
  google_mobile_ads: ^6.0.0

  # Charts
  fl_chart: ^1.0.0

  # State management
  provider: ^6.1.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3   
  # WebView (optional, if you plan to use it)
  webview_flutter: ^4.13.0
